services:
    DB:
        image: mariadb:latest
        container_name: DB
        restart: always
        networks: 
          - network
        volumes:
            - ~/docker/mariadb/conf.d:/etc/mysql/conf.d
            - ~/docker/mariadb/data:/var/lib/mysql
        environment:
            - MYSQL_HOST=localhost
            - MYSQL_PORT=3306
            - MYSQL_ROOT_PASSWORD=1234
            - MYSQL_DATABASE=edu
            - MYSQL_USER=folder
            - MYSQL_PASSWORD=1234
    APP:
        image: openjdk:latest
        container_name: APP
        depends_on: 
          - DB
        restart: always
        ports: 
          - 8080:8080
        networks: 
          - network
        links: 
          - DB
        volumes: 
          - ~/docker/spring:/usr/local
        command: java -jar /usr/local/app.jar
networks:
    network: